version: 1.0.{build}
os: Visual Studio 2022
install:
- git submodule update --init --recursive
build_script:
- msbuild /r /m /bl
- gradlew.bat -is nunit nugetPack
test: off
artifacts:
  - path: 'build\distributions\*.nupkg'
    name: Nuget
  - path: 'msbuild.binlog'
    name: 'MSBuild binlog'
on_failure:
- appveyor PushArtifact msbuild.binlog